### ISSUE TITLE
Serializing abstract class

### ISSUE THREAD

**Issue by NuclearCookie** [ncannasse/hxbit#10]
Hi Nicolas,

I need to serialize a quite specific file: a `Float32Array`.
The file is an abstract and I'm lost on how to make it serializable...

https://github.com/FishingCactus/lime/blob/develop/lime/utils/Float32Array.hx

Can you give some feedback?

Thanks

**Comment by ncannasse** [comment]
Not straightforward. You need first to switch to more generic Haxe version haxe.ds.Float32Array, then you need to modify hxbit to detect these types (all XXXArrays) and serialize/unserialize the underlying bytes (see hxbit.Macros).

It will be easier if you use `Array<Single>` instead

**Comment by NuclearCookie** [comment]
Ok thank you. Is there a way of doing custom serialization? Like the `hxSerialize` and `hxUnserialize` functions of the `haxe.Serializer` ? That would also fix my problem

**Comment by ncannasse** [comment]
That's a good idea, not much time atm but I'll keep it in mind when I work on hxbit

**Comment by ncannasse** [comment]
PS: if you want to do it by yourself, use an interface CustomSerializable and detect it with the macros the way I detect Serializable

**Comment by NuclearCookie** [comment]
Thank you. I will definitely take a look at that soon. I'll keep you posted

**Comment by NuclearCookie** [comment]
I have a first implementation running. Once i've been able to properly test it, I'll make a pull request
