### ISSUE TITLE
how to deal with proxy types being invalid when passed to a function?

### ISSUE THREAD

**Issue by Coderah** [ncannasse/hxbit#14]
given this type:

```
typedef TPosition = {
    x: Int,
    y: Int
}
```

the following will throw an error compiling to c++

```
class Test extends hxbit.NetworkSerializable {
    @:s position: TPosition = { x: 0, y: 0 }

    public function test() {
        Logic.checkPosition(position);
    }
}

class Logic {
    public static function checkPosition(pos: TPosition) {
        // do something with pos

        return false;
    }
}
```

error:
```
hxbit.ObjProxy_x_Int_y_Int should be TPosition
hxbit.ObjProxy_x_Int_y_Int should be { y : Int, x : Int }
inconsistent setter for field x : set should be default For function argument 'pos'
```

the example provided is not a direct copy (might not run) but is written to provide clarity on the issue.

**Comment by ncannasse** [comment]
Yes, we need to wrap the object with a proxy to track its changes.
If you can allow it, you can replace `pos : TPosition` by `pos : hxbit.Proxy<TPosition>`. Now that's a problem if you want to accept both proxied and not proxied versions. I might need to add a function to proxy to get back the original object, but with a name that tells you you shouldn't mutate it.
Any suggestion?

**Comment by Coderah** [comment]
Hey @ncannasse that worked really solidly, not sure why I forgot about the proxying of the type.

Yeah I can see how that might be a need, I haven't hit it for sure though so I'll let you know as I get further in the project if it makes sense and I can come up with a possible suggestion.

Thanks!
