### ISSUE TITLE
1.3.0 Type not found: hxd.Math

### ISSUE THREAD

**Issue by Coderah** [ncannasse/hxbit#16]
On the latest version I'm getting this type error on builds:

`/home/coderah/haxelib/hxbit/1,3,0/hxbit/NetworkStats.hx:92: characters 88-91 : Type not found : hxd.Math`

still a little new to Haxe but sounds like a missing lib?

**Comment by ncannasse** [comment]
Thanks for reporting, it was a mistake of my part (using hxbit + heaps), I have published 1.3.1 update on haxelib.

**Comment by Coderah** [comment]
Awesome! Thanks for the fix, I was hoping it was simple :)
