### ISSUE TITLE
JS: makeAlive Std.Instance check incorrect.

### ISSUE THREAD

**Issue by Coderah** [ncannasse/hxbit#18]
This code [NetworkHost:544](https://github.com/ncannasse/hxbit/blob/master/hxbit/NetworkHost.hx#L544) will always return `false` due to the way [createEmptyInstance](http://api.haxe.org/Type.html#createEmptyInstance) works in the JS implementation at [Serializer.hx:473](https://github.com/ncannasse/hxbit/blob/master/hxbit/Serializer.hx#L473)

```
       public static function createEmptyInstance<T>( cl : Class<T> ) : T untyped {
		__js__("function empty() {}; empty.prototype = cl.prototype");
		return __js__("new empty()");
	}
```

I'm not sure the best approach to fixing this, I'll likely do a hacky fix for the time being, potentially more of a Haxe JS implementation issue than hxbit?

**Comment by ncannasse** [comment]
Yes it's more an haxe issue. Please open an one there that tells that using Type.createEmptyInstance + Std.instance doesn't work in JS.
