### ISSUE TITLE
not usable in macro context

### ISSUE THREAD

**Issue by francescoagati** [ncannasse/hxbit#2]
Hi,
inside macro context hxbit can't be used because of @:genericBuild cannot be used in macros in line Serializable.hx:44

**Comment by ncannasse** [comment]
Yes it's a normal restriction when dealing with build macros, why do you want to use hxbit inside macros ?

**Comment by francescoagati** [comment]
I want use it inside macro for serialize ast methods. But i have resolve with normal haxe serialization
