### ISSUE TITLE
no Unserializer

### ISSUE THREAD

**Issue by liminalitythree** [ncannasse/hxbit#22]
There is no class 'Unserializer' in this library. What's the point of serializing things if you can't reverse it? haxe is giving me the error 'Type not found : hxbit.Unserializer' and if I look in your source, there is a hxbit.Serializer but no hxbit.Unserializer. is this somewhere else or is the library not ready for use yet?

**Comment by ncannasse** [comment]
RTFM ;) https://github.com/ncannasse/hxbit/blob/master/README.md

**Comment by ncannasse** [comment]
Ah, there was actually a typo in then README, I have fixed it: you should use Serializer to unserialize as well.
