### ISSUE TITLE
Issue when compiling

### ISSUE THREAD

**Issue by jinjinjinK** [ncannasse/hxbit#8]
I'm trying to use this to serialize packet to send for a p2p network but I get this errors.

Serializer.cpp
./src/hxbit/Serializer.cpp(194) : error C2039: '__clid' : is not a member of 'hx::Class_obj'
        C:\HaxeToolkit\haxe\lib\hxcpp\3,4,64\include\hx/Class.h(98) : see declaration of 'hx::Class_obj'
./src/hxbit/Serializer.cpp(194) : error C2660: 'hxbit::Serializer_obj::getRef' : function does not take 1 arguments
./src/hxbit/Serializer.cpp(1371) : error C2039: '__clid' : is not a member of 'hx::Class_obj'
        C:\HaxeToolkit\haxe\lib\hxcpp\3,4,64\include\hx/Class.h(98) : see declaration of 'hx::Class_obj'
./src/hxbit/Serializer.cpp(1402) : error C2039: '__clid' : is not a member of 'hx::Class_obj'
        C:\HaxeToolkit\haxe\lib\hxcpp\3,4,64\include\hx/Class.h(98) : see declaration of 'hx::Class_obj'
./src/hxbit/Serializer.cpp(1402) : error C2660: 'hxbit::Serializer_obj::getRef' : function does not take 1 arguments
./src/hxbit/Serializer.cpp(1742) : error C2039: '__clid' : is not a member of 'hx::Class_obj'
        C:\HaxeToolkit\haxe\lib\hxcpp\3,4,64\include\hx/Class.h(98) : see declaration of 'hx::Class_obj'
./src/hxbit/Serializer.cpp(1742) : error C2660: 'hxbit::Serializer_obj::getRef' : function does not take 1 arguments

**Comment by ncannasse** [comment]
I don't seem to be able to reproduce using latest Haxe + HxBit, I guess this is something that has been fixed in hxcpp (ping @hughsando)
